// data.js

/**
 * --- Configuration, Data Storage, and Constants ---
 */

"use strict";

// Language translation dictionary
const translations = {
    'en': {
        'organisation': 'Paschim Banga Vigyan Mancha',
        'nav_menu': 'Menu',
        'nav_home': 'Home',
        'nav_about': 'About',
        'nav_projects': 'Projects',
        'nav_publications': 'Publications',
        'nav_download': 'Download',
        'nav_contact': 'Contact',
        'nav_events': 'Events',
        'nav_rank': 'Rank',
        'nav_admit': 'Admit Card',
        'install': ' Install App',
        'carousel_home_name': 'Welcome',
        'carousel_home_des': 'Uluberia Vigyan Kendra',
        'carousel_home_btn': "See What's New",
        'carousel_donate_btn': 'Donate to us',
        'carousel_about_name': 'About',
        'carousel_about_des': 'Learn about us here.',
        'carousel_about_btn': 'Learn About Us',
        'carousel_projects_name': 'Projects',
        'carousel_projects_des': 'Our ongoing and past projects.',
        'carousel_projects_btn': 'View Projects',
        'carousel_publications_name': 'Publications',
        'carousel_publications_des': 'Read our publications and research.',
        'carousel_publications_btn': 'Read Publications',
        'carousel_download_name': 'Download',
        'carousel_download_des': 'Get downloadable resources here.',
        'carousel_download_btn': 'Get Resources',
        'carousel_contact_name': 'Contact',
        'carousel_contact_des': 'Reach out to us anytime.',
        'carousel_contact_btn': 'Get in Touch',
        'donate_title': 'Support Our Mission',
        'donate_choose_amount': 'Choose Amount:',
        'other_amnt': 'Other',
        'donate_scan_qr': 'Scan the QR code below.',
        'donate_open_upi': 'Open in UPI App',
        'donate_upi_id_label': 'UPI ID:',
        'donate_copy_upi': 'Copy UPI ID',
        'donate_note': 'Your generous contribution directly funds our science popularization and community projects.',
        'book_type_magazine': 'Type: Recurring Magazine',
        'book_type_standard': 'Type: Standard Publication',
        'book_no_description': 'No description available for this publication.',
        'book_btn_buy': 'Buy Now',
        'book_btn_subscribe': 'Subscribe',
        'book_btn_download': 'Download / Read More',
        'msg_subscription': 'Subscription will start from 1st August 2026. Thank you for your interest!',
        'msg_purchase_dev': 'Purchase/Download feature is under development.',
        'msg_subscribe_dev': 'Subscription feature is under development. Thank you for your interest!',
        'msg_upi_copied': 'UPI ID copied to clipboard!',
        'msg_upi_fail': 'Failed to copy UPI ID.',
        'pub_subscribe_prompt': 'Want to enjoy our regular magazines? Subscribe today!',
        'pub_subscribe_btn': 'Become a Subscriber',
        'pub_featured_title': 'Featured Books',
        'pub_error_loading': 'Error loading publications. Please check your connection and try again.',
        'notice_title': 'Important Notice',
        'notice_subtitle_en': 'Current Events',
        'notice_subtitle_bn': 'Current Events',
        'exam': 'Howrah Zilla Vigyan Manosikata-o-Medha Aviksha',
        'uluberia': 'Uluberia Vigyan Kendra',
        'nav_result': 'Result',
        'result_finder_title': 'Result Finder',
        'result_finder_subtitle': 'Enter your Roll Number to view your results.',
        'result_header': 'Performance Report - Howrah Zilla Vigyan Manosikata-o-Medha Aviksha - ',
        'roll_number_label': 'Roll Number',
        'roll_number_placeholder': 'e.g. UL/12345',
        'search_result_button': 'Search Result',
        'print_result_button': 'Print Result',
        'your_result_heading': 'Your Result',
        'searching_text': 'Searching...',
        'year_label': 'Year',
        'year_placeholder': 'e.g. 2024',
        'roll': 'Roll Number:',
        'name': 'Name:',
        'school': 'School:',
        'class': 'Class:',
        'marks': 'Marks Obtained:',
        'grade': 'Grade:',
        'not_found': '❌ Roll Number not found in the sheet.',
        'api_error': '🚨 API Error: ${data.message}',
        'error_found': '❌ Result is not available for this year.',
        'network_error': '🚨 Critical Network Error: ${error.message}. Check browser console.',
        'enter_roll_number': 'Please enter a valid Roll Number. e.g., UL/12345',
        'default_result_display': 'Please enter your Roll Number above and click Search Result to view your performance.',
        'loading_blog_posts': 'Loading blog posts...',
        'no_more_posts': 'No more posts',
        'previous_button': '« Previous',
        'next_button': 'NEXT »',
        'tag-all': 'All',
        'tag-2025': '2025',
        'tag-40': '40 years',
        'tag-adda': 'Science Adda',
        'tag-aviksha': 'Aviksha',
        'tag-adultration': 'Adultration',
        'tag-sky': 'Sky Watching',
        'tag-vday': 'National Science Day',
        'tag-pday': 'World Environment Day',
        'tag-treeWeek': 'Forest Week',
        'tag-antiSup': 'Anti Superstition',
        'btn_read_more': 'READ MORE »',
        'popular_posts': 'Popular Posts',
        'tags': 'Tags',
        'important_01': 'Four decades of scientific popularization.',
        'name_label': 'Enter Name',
        'name_placeholder': 'Student Name',
        'school_placeholder': 'Select School',
        'admit_card': 'Admit Card',
        'previous_paper': 'Previous Paper',
        'no_students_found': 'No students found.',
    },
    'bn': {
        'organisation': 'পশ্চিমবঙ্গ বিজ্ঞান মঞ্চ',
        'nav_menu': 'মেনু',
        'nav_home': 'হোম',
        'nav_about': 'আমাদের কথা',
        'nav_projects': 'কর্মসূচী',
        'nav_publications': 'প্রকাশনা',
        'nav_download': 'ডাউনলোড',
        'nav_contact': 'যোগাযোগ',
        'nav_events': 'কার্যক্রম',
        'nav_rank': 'মেধাক্রম',
        'install': ' অ্যাপ ইন্সটল করুন',
        'carousel_home_name': 'স্বাগতম',
        'carousel_home_des': 'উলুবেড়িয়া বিজ্ঞান কেন্দ্র',
        'carousel_home_btn': 'নতুন কি দেখুন',
        'carousel_donate_btn': 'অনুদান',
        'carousel_about_name': 'আমাদের কথা',
        'carousel_about_des': 'আমাদের সম্পর্কে এখানে জানুন।',
        'carousel_about_btn': 'আমাদের সম্পর্কে জানুন',
        'carousel_projects_name': 'কর্মসূচী',
        'carousel_projects_des': 'আমাদের বর্তমান এবং অতীত কর্মসূচী সমুহ।',
        'carousel_projects_btn': 'কর্মসূচী সম্পর্কে জানুন',
        'carousel_publications_name': 'প্রকাশনা',
        'carousel_publications_des': 'আমাদের প্রকাশনাগুলি পড়ুন।',
        'carousel_publications_btn': 'প্রকাশনা পড়ুন',
        'carousel_download_name': 'ডাউনলোড',
        'carousel_download_des': 'ডাউনলোডযোগ্য নথিগুলি এখানে পান।',
        'carousel_download_btn': 'বিস্তারিত দেখুন',
        'carousel_contact_name': 'যোগাযোগ',
        'carousel_contact_des': 'যেকোনো সময় আমাদের সাথে যোগাযোগ করুন।',
        'carousel_contact_btn': 'যোগাযোগ করুন',
        'donate_title': 'আমাদের পাশে দাঁড়ান',
        'donate_choose_amount': 'পরিমাণ চয়ন করুন:',
        'other_amnt': 'পছন্দসই',
        'donate_scan_qr': 'নীচের QR কোড স্ক্যান করুন।',
        'donate_open_upi': 'UPI অ্যাপে খুলুন',
        'donate_upi_id_label': 'UPI ID:',
        'donate_copy_upi': 'UPI ID কপি করুন',
        'donate_note': 'আপনার সহযোগীতা সরাসরি আমাদের বিজ্ঞান জনপ্রিয়করণ এবং কার্যকলাপগুলিকে অর্থায়ন করে।',
        'book_type_magazine': 'ধরন: ধারাবাহিক পত্রিকা',
        'book_type_standard': 'ধরন: বই',
        'book_no_description': 'এই প্রকাশনার জন্য কোন বিবরণ উপলব্ধ নেই।',
        'book_btn_buy': 'এখনই কিনুন',
        'book_btn_subscribe': 'গ্রাহক হন',
        'book_btn_download': 'ডাউনলোড / আরও পড়ুন',
        'msg_purchase_dev': 'ক্রয়/ডাউনলোড বৈশিষ্ট্যটি নির্মাণাধীন।',
        'msg_subscription': '১লা আগষ্ট, ২০২৬ থেকে সাবস্ক্রিপশন শুরু হবে। আপনার আগ্রহের জন্য ধন্যবাদ!',
        'msg_subscribe_dev': 'সাবস্ক্রিপশন বৈশিষ্ট্যটি নির্মাণাধীন। আপনার আগ্রহের জন্য ধন্যবাদ!',
        'msg_upi_copied': 'UPI ID ক্লিপবোর্ডে কপি করা হয়েছে!',
        'msg_upi_fail': 'UPI ID কপি করতে ব্যর্থ।',
        'pub_subscribe_prompt': ' আপনি কি আমাদের নিয়মিত পত্রিকা উপভোগ করতে চান? আজই গ্রাহক হন!',
        'pub_subscribe_btn': 'গ্রাহক হন',
        'pub_featured_title': ' পত্রিকা ও বই',
        'pub_error_loading': 'প্রকাশনা লোড করতে ত্রুটি। অনুগ্রহ করে আপনার সংযোগ পরীক্ষা করুন এবং আবার চেষ্টা করুন।',
        'notice_title': 'গুরুত্বপূর্ণ বিজ্ঞপ্তি',
        'notice_subtitle_en': 'বর্তমান ঘটনাবলী',
        'notice_subtitle_bn': 'বর্তমান ঘটনাবলী',
        'exam': 'হাওড়া জেলা বিজ্ঞান মানসিকতা ও মেধা অভীক্ষা',
        'uluberia': 'উলুবেড়িয়া বিজ্ঞান কেন্দ্র',
        'nav_result': 'ফলাফল',
        'nav_admit': 'অ্যাডমিট কার্ড',
        'result_finder_title': 'ফলাফল অনুসন্ধান',
        'result_finder_subtitle': 'আপনার ফলাফল দেখতে রোল নম্বর লিখুন।',
        'result_header': 'ফলাফল - হাওড়া জেলা বিজ্ঞান মানসিকতা ও মেধা অভীক্ষা - ',
        'result_year': 'বছর',
        'roll_number_label': 'রোল নম্বর',
        'year_label': 'বছর',
        'year_placeholder': 'যেমন: 2024',
        'roll_number_placeholder': 'যেমন: UL/12345',
        'search_result_button': 'ফলাফল খুঁজুন',
        'print_result_button': 'ফলাফল প্রিন্ট করুন',
        'your_result_heading': 'আপনার ফলাফল',
        'searching_text': 'অনুসন্ধান চলছে...',
        'roll': 'রোল নম্বর:',
        'name': 'নাম:',
        'school': 'বিদ্যালয়:',
        'class': 'শ্রেণী:',
        'marks': 'প্রাপ্ত নম্বর:',
        'grade': 'গ্রেড:',
        'not_found': '❌ এই রোল নম্বরটি নেই।',
        'api_error': '🚨 API বিভ্রাট: ${data.message}',
        'error_found': '❌ এই বছরের ফলাফল উপলব্ধ নেই।',
        'network_error': '🚨 গুরুত্বপূর্ণ বিভ্রাট: ${error.message}. ব্রাউজার কনসোল চেক করুন।',
        'enter_roll_number': 'আপনি রোল নম্বরটি ঠিক লেখেন নি। যেমন: UL/12345',
        'default_result_display': 'আপনার ফলাফল দেখতে সঠিক রোল নম্বর লিখুন।',
        'loading_blog_posts': 'ব্লগ পোস্ট লোড হচ্ছে...',
        'no_more_posts': 'আর কোনো পোস্ট নেই',
        'previous_button': '« পূর্বের',
        'next_button': 'পরের »',
        'tag-all': 'সব',
        'tag-2025': '২০২৫',
        'tag-40': '৪০ বছর',
        'tag-aviksha': 'অভিক্ষা',
        'tag-adda': 'বিজ্ঞান আড্ডা',
        'tag-sky': 'আকাশ দেখো',
        'tag-adultration': 'ভেজাল',
        'tag-antiSup': 'কুসংস্কার বিরোধী অভিযান',
        'tag-vday': 'জাতীয় বিজ্ঞান দিবস',
        'tag-pday': 'বিশ্ব পরিবেশ দিবস',
        'tag-treeWeek': 'অরণ্য সপ্তাহ',
        'no_more_posts': 'এই ট্যাগের সাথে আর কোনো প্রতিবেদন নেই।',
        'btn_read_more': 'বিস্তারিত দেখুন »',
        'popular_posts': 'বিশেষ প্রতিবেদন',
        'tags': 'ট্যাগস',
        'important_01': 'বিজ্ঞানকে জনপ্রিয় করার চার দশক',
        'name_label': 'পরীক্ষার্থীর নাম',
        'name_placeholder': 'নাম লিখুন',
        'admit_card': 'অ্যাডমিট কার্ড',
        'previous_paper': 'পূর্বের প্রশ্নাবলী',
        'school_placeholder': 'বিদ্যালয়ের নাম বেছে নিন',
        'no_students_found': 'এই নামে কোনো পরীক্ষার্থী নেই।',
    }
};

const JSON_URL_EN = "https://gist.githubusercontent.com/pbvmuluberia/b6bf520cce8c1b0167a6657b2c60e4d2/raw/de662cd94dc4b4ff0f83aed00461851370a651f8/book.json";
const JSON_URL_BN = "https://gist.githubusercontent.com/pbvmuluberia/e5e2122ddf3ac7489e61be9f81e475fd/raw/32e1b563d2e57a0417da5bd4dbe868089acae575/book_bn.json";

// Global data store for fetched book data
window.bookData = { en: null, bn: null };

// UPI payment constants
const UPI_ID = '9433361030@ucobank';
const VPA_NAME = 'Paschim Banga Vigyan Mancha (Uluberia Vigyan Kendra)';

// State variables
let currentDonationAmount = 100;
let isInitialized = false;

// Attach translations to window for access in other files
window.translations = translations;
window.JSON_URL_EN = JSON_URL_EN;
window.JSON_URL_BN = JSON_URL_BN;
window.UPI_ID = UPI_ID;
window.VPA_NAME = VPA_NAME;
window.currentDonationAmount = currentDonationAmount;
window.isInitialized = isInitialized;


